import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.css';
import { Hero, PHRASES } from './Hero'
import { JSONFilePreset } from 'lowdb/node';
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export async function readHeroes(name: string) {
  const defaultData: Hero[] = [];
  const db = await JSONFilePreset(name, defaultData);
  return db;
}




export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const db = await readHeroes('./data/heroes.json')

  return (
    <html lang="en" data-bs-theme="dark">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <a href="/">Learn</a><a href="/quiz">Quiz</a>
        <Link href={{
                pathname: '/quiz',
                query: { hero: "db.data" },
            }}>
                Quiz
            </Link>
        {children}
        
      </body>
    </html>
  );
}
